# Generated by Django 5.1.3 on 2024-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('primary_type', models.CharField(max_length=100)),
                ('canonical_url', models.URLField()),
                ('urlid', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('states', models.CharField(max_length=100)),
            ],
        ),
    ]
