# Generated by Django 5.1.3 on 2024-11-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_evento_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoevento',
            options={'verbose_name_plural': 'Tipos de Eventos'},
        ),
    ]
